# GitHub Sponsors'ı etkinleştirmek için bu dosyayı düzenleyin.
# Desteklemek istediğiniz platformları buraya ekleyin.
# Örnekler:
# github: [username1, username2]
# patreon: username
# open_collective: projectname
# custom: ["https://example.com/donate"]

github: [nisankoltukyikamacom-art]
